Cleaned up language in Specificaions
c2pa-org/specifications pull request #69
Opened 2024-10-08 20:54 UTC by Brianthered

Doing initial read through of the specifications in v 2.1.  
Broke up run on sentence to be more readable.  
Fixed pluralization noun verb agreement.

2024-10-08 21:20 UTC, lrosenthol commented
@Brianthered thanks for the PR.  Will take a look and see about applying them where appropriate!

2024-10-27 22:17 UTC, lrosenthol requested changes

2024-10-27 22:17 UTC, lrosenthol commented on build/site/specifications/2.1/specs/C2PA_Specification.html
> +C2PA specifications SHOULD NOT provide value judgments about whether a given set of provenance data is 'good' or 'bad'.  The assertions can be: validated as associated with the underlying asset, can
I prefer the current text - what is the concern here?

2024-10-27 22:17 UTC, lrosenthol commented on build/site/specifications/2.1/specs/C2PA_Specification.html
> +<p>Content Credentials can also refer to the overall C2PA technology.  If a <a href="#_c2pa_manifest">C2PA Manifest</a> is a Content Credential, then multiple <a href="#_c2pa_manifest">C2PA Manifests
Content Credentials ALWAYS refers to the technology - can implies a choice. Also, the grammar is important about the plural noun

What are your concerns with this text?

2025-08-10 09:59 UTC, stonigrl approved these changes

2026-04-07 01:38 UTC, closed without merging